e55a9721122e
*** Found local files:
***   * /opt/airflow/logs/dag_id=5be51295-3c29-433b-8ba9-8c4653955b26/run_id=manual__2024-09-09T07:36:05+00:00/task_id=ingestion_task/attempt=1.log
[2024-09-09T07:36:06.405+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-09T07:36:06.436+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 5be51295-3c29-433b-8ba9-8c4653955b26.ingestion_task manual__2024-09-09T07:36:05+00:00 [queued]>
[2024-09-09T07:36:06.445+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 5be51295-3c29-433b-8ba9-8c4653955b26.ingestion_task manual__2024-09-09T07:36:05+00:00 [queued]>
[2024-09-09T07:36:06.445+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-09-09T07:36:06.464+0000] {taskinstance.py:2330} INFO - Executing <Task(CustomPythonOperator): ingestion_task> on 2024-09-09 07:36:05+00:00
[2024-09-09T07:36:06.474+0000] {standard_task_runner.py:63} INFO - Started process 11540 to run task
[2024-09-09T07:36:06.479+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', '5be51295-3c29-433b-8ba9-8c4653955b26', 'ingestion_task', 'manual__2024-09-09T07:36:05+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/5be51295-3c29-433b-8ba9-8c4653955b26.py', '--cfg-path', '/tmp/tmp33ishqbv']
[2024-09-09T07:36:06.480+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask ingestion_task
[2024-09-09T07:36:06.528+0000] {task_command.py:426} INFO - Running <TaskInstance: 5be51295-3c29-433b-8ba9-8c4653955b26.ingestion_task manual__2024-09-09T07:36:05+00:00 [running]> on host e55a9721122e
[2024-09-09T07:36:06.622+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='5be51295-3c29-433b-8ba9-8c4653955b26' AIRFLOW_CTX_TASK_ID='ingestion_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-09T07:36:05+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-09T07:36:05+00:00'
[2024-09-09T07:36:06.622+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-09T07:36:06.658+0000] {server_mixin.py:74} INFO - OpenMetadata client running with Server version [1.5.2] and Client version [1.5.2.0]
[2024-09-09T07:36:06.979+0000] {aws_client.py:147} INFO - Getting AWS client for service [s3]
[2024-09-09T07:36:07.088+0000] {aws_client.py:147} INFO - Getting AWS client for service [cloudwatch]
[2024-09-09T07:36:07.494+0000] {test_connections.py:221} INFO - Test connection results:
[2024-09-09T07:36:07.494+0000] {test_connections.py:222} INFO - failed=[] success=["'ListBuckets': Pass", "'GetMetrics': Pass"] warning=[]
[2024-09-09T07:36:08.527+0000] {metadata.py:694} INFO - Looking for metadata template file at - s3://etlhunter/openmetadata.json
[2024-09-09T07:36:08.545+0000] {metadata.py:706} WARNING - No metadata file found at s3://etlhunter/openmetadata.json
[2024-09-09T07:36:08.720+0000] {logger.py:175} INFO - [1mWorkflow S3 Summary:[0m
[2024-09-09T07:36:08.721+0000] {logger.py:175} INFO - Processed records: 0[0m
[2024-09-09T07:36:08.721+0000] {logger.py:175} INFO - Updated records: 0[0m
[2024-09-09T07:36:08.721+0000] {logger.py:175} INFO - Warnings: 0[0m
[2024-09-09T07:36:08.721+0000] {logger.py:175} INFO - Errors: 0[0m
[2024-09-09T07:36:08.721+0000] {logger.py:175} INFO - [1mWorkflow OpenMetadata Summary:[0m
[2024-09-09T07:36:08.721+0000] {logger.py:175} INFO - Processed records: 0[0m
[2024-09-09T07:36:08.722+0000] {logger.py:175} INFO - Updated records: 0[0m
[2024-09-09T07:36:08.722+0000] {logger.py:175} INFO - Warnings: 0[0m
[2024-09-09T07:36:08.722+0000] {logger.py:175} INFO - Errors: 0[0m
[2024-09-09T07:36:08.723+0000] {logger.py:175} INFO - [1m[36;1mSuccess %: 100.0[0m
[2024-09-09T07:36:08.723+0000] {logger.py:175} INFO - [1m[36;1mWorkflow finished in time: 1.75s[0m
[2024-09-09T07:36:08.724+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-09-09T07:36:08.791+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-09-09T07:36:08.814+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-09T07:36:08.815+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
